name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.4.app
    - name: Build
      run: swift build -v
    - name: Build release
      run: swift build -v -c release
